baseURL = "https://kkren.me/"
languageCode = "en-us"
title = "about kkren"
theme        = "hello-friend-ng"
paginate     = 10
disableKinds = ["RSS"]
[author]
  name = "kkren"
[params]
  dateform        = "Jan 2, 2006"
  dateformShort   = "Jan 2"
  dateformNum     = "2006-01-02"
  dateformNumTime = "2006-01-02 15:04"

  # Set disableReadOtherPosts to true in order to hide the links to other posts.
  disableReadOtherPosts = false

  # Enable sharing buttons, if you like
  enableSharingButtons = true

  images = ["avatar.png"]
  # Social icons

  [[params.social]]
    name = "email"
    url  = "mailto:i@kkren.me"

  [[params.social]]
    name = "github"
    url  = "https://github.com/kkren"

  [[params.social]]
    name = "telegram"
    url  = "https://t.me/kkren"

  [[params.social]]
    name = "twitter"
    url  = "https://twitter.com/kkren001/"
 
  [params.portrait]
    path     = "/avatar.webp"
    alt      = "avatar"
    maxWidth = "100px"

    [params.logo]
        logoText = "$ cd /home/kkren"
        logoHomeLink = "/"

[taxonomies]
    category = "blog"
    tag      = "tags"
    series   = "series"

[languages]
  [languages.en]
    title = "KKren"
    subtitle = ""
    keywords = ""
    copyright = '<a href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank" rel="noopener">CC BY-NC 4.0</a>'
    homeSubtitle = "A newbie programer"


[menu]
  # And you can even create generic menu
  [[menu.main]]
    name       = "Blog"
    url        = "https://blog.kkren.me"
    weight = 1
